version: '3'
services:
   mysql:
    container_name: mysql
    build: src/main/resources/db/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    restart: always
    volumes:
      - data:/var/lib/mysql

   spring:
    container_name: spring
    build: .
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

volumes:
  data:
